name: solo
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py==2.7.0
  - Keras==2.1.2
  - numpy==1.13.3
  - scikit-image==0.13.0
  - scikit-learn==0.19.1
  - scipy==0.19.1
  - tensorflow-gpu==1.4.1
  - opencv==3.4.1
  - yaml==0.2.5